services:
  bankchecker:
    build:
      context: https://github.com/stephenyctsedev/bankchecker.git
    container_name: bank-statement-checker
    ports:
      - "8501:8501"
    restart: unless-stopped
